ALTER TABLE ASIGNATURAS_MATRICULA DROP FOREIGN KEY FK_ASIGNATURAS_MATRICULA_CURSO_ACADEMICO
ALTER TABLE ASIGNATURAS_MATRICULA DROP FOREIGN KEY FK_ASIGNATURAS_MATRICULA_GRUPO_ID
ALTER TABLE ASIGNATURA DROP FOREIGN KEY FK_ASIGNATURA_ASIGNATURAS_TITULACION_CODIGO
ALTER TABLE EXPEDIENTES DROP FOREIGN KEY FK_EXPEDIENTES_TITULACION_CODIGO
ALTER TABLE EXPEDIENTES DROP FOREIGN KEY FK_EXPEDIENTES_ALUMNO_ID
ALTER TABLE MATRICULA DROP FOREIGN KEY FK_MATRICULA_EXPEDIENTE_NUM_EXPEDIENTE
ALTER TABLE ENCUESTA DROP FOREIGN KEY FK_ENCUESTA_EXPEDIENTE_NUM_EXPEDIENTE
ALTER TABLE CLASE DROP FOREIGN KEY FK_CLASE_GRUPO_ID
ALTER TABLE GRUPO DROP FOREIGN KEY FK_GRUPO_TITULACION_CODIGO
ALTER TABLE GRUPO_POR_ASIGNATURA DROP FOREIGN KEY FK_GRUPO_POR_ASIGNATURA_GRUPO_ID
ALTER TABLE OPTATIVAS DROP FOREIGN KEY FK_OPTATIVAS_ASIGNATURAS_TITULACION_CODIGO
ALTER TABLE jnd_titu_cen DROP FOREIGN KEY FK_jnd_titu_cen_titu_fk
ALTER TABLE jnd_titu_cen DROP FOREIGN KEY FK_jnd_titu_cen_cen_fk
ALTER TABLE GRUPO_POR_ASIGNATURA_ENCUESTA DROP FOREIGN KEY FK_GRUPO_POR_ASIGNATURA_ENCUESTA_CURSO_ACADEMICO
ALTER TABLE GRUPO_POR_ASIGNATURA_ENCUESTA DROP FOREIGN KEY GRUPOPORASIGNATURA_ENCUESTAencuesta_FECHA_DE_ENVIO
ALTER TABLE GRUPO_GRUPO DROP FOREIGN KEY FK_GRUPO_GRUPO_agrupa_grupos_ID
ALTER TABLE GRUPO_GRUPO DROP FOREIGN KEY FK_GRUPO_GRUPO_Grupo_ID
DROP TABLE ASIGNATURAS_MATRICULA
DROP TABLE ASIGNATURA
DROP TABLE TITULACION
DROP TABLE EXPEDIENTES
DROP TABLE MATRICULA
DROP TABLE ENCUESTA
DROP TABLE CENTRO
DROP TABLE CLASE
DROP TABLE GRUPO
DROP TABLE GRUPO_POR_ASIGNATURA
DROP TABLE OPTATIVAS
DROP TABLE ALUMNO
DROP TABLE jnd_titu_cen
DROP TABLE GRUPO_POR_ASIGNATURA_ENCUESTA
DROP TABLE GRUPO_GRUPO
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
