package es.uma.informatica.sii.trabajo.tests;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;



import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;

import javax.ws.rs.client.ClientBuilder;
import javax.ws.rs.client.WebTarget;

import java.net.MalformedURLException;
import java.net.URL;

public class DefaultSuiteIT {
	private static final String UNIDAD_PERSISTENCIA = "TrabajoTest";
	private static final String CONTEXT_ROOT = "http://0.0.0.0:8080/trabajo-war";

	//private static final String CUENTA_PRUEBA = "antonio";
	//private static final String CONTRASENIA = "antonio";

	private static WebTarget uri;

	@BeforeClass
	public static void setupClass() {
		uri = ClientBuilder.newClient().target(CONTEXT_ROOT);
	}

	@Before
	public void setup() {
		BaseDeDatos.inicializar("TrabajoTest");
	}
	
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void prueba2IT() {
    driver.get("http://0.0.0.0:8080/trabajo-war/");
    driver.manage().window().setSize(new Dimension(550, 696));
    driver.findElement(By.id("login:user")).click();
    driver.findElement(By.id("login:user")).sendKeys("123");
    driver.findElement(By.id("login:psw")).click();
    driver.findElement(By.id("login:psw")).sendKeys("123");
    driver.findElement(By.name("login:j_idt15")).click();
    assertThat(driver.findElement(By.cssSelector(".formInputError")).getText(), is("La cuenta no existe"));
  }
}