package es.uma.informatica.sii.trabajo.tests;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import es.uma.informatica.sii.anotaciones.Requisitos;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class VerSolicitudIT {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  @Requisitos({"RF8"})
  public void solic() {
    driver.get("http://0.0.0.0:8080/trabajo-war/versolicitud.xhtml");
    driver.manage().window().setSize(new Dimension(550, 544));
    //driver.findElement(By.id("j_idt6")).click();
    //driver.findElement(By.cssSelector("tr:nth-child(1) > th:nth-child(3)")).click();
    //driver.findElement(By.cssSelector("tr:nth-child(1) > th:nth-child(2)")).click();
    //driver.findElement(By.id("j_idt6")).click();
    driver.findElement(By.id("j_idt6:versolivolver")).click();
  }
}
